---
# https://developer.hashicorp.com/vagrant/downloads
- name: Download GPG key
  ansible.builtin.shell: wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  become: true

- name: Doesn't support Newest Ubuntu! If > 22.10, Set to kinetic.
  set_fact:
    codename: "{{ ubuntu_latest_supported_codename }}"
  when: (ansible_distribution_version | replace('.','') | int) >= ubuntu_latest_supported

- name: Add repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ codename }} main"
    state: present
    filename: hashicorp
  become: true

- name: Install Vagrant
  ansible.builtin.apt:
    pkg:
    - vagrant
  become: true
