---
# May not need this anymore

- name: Add repository, If Fedora_Beta
  become: true
  ansible.builtin.template:
    src: Fedora_Beta-hashicorp.repo.j2
    dest: /etc/yum.repos.d/hashicorp.repo
  when: ansible_distribution_major_version | int == Fedora_Beta

