---
- hosts: localhost
  vars:
    dir: ".uni/vm"
    repo: [
      { subdir: "{{dir}}", name: "Vagrant", repo: "git@github.com:Unicorn-OS/Vagrant.git"},
      { subdir: "{{dir}}", name: "vagrant.template", repo: "git@github.com:Unicorn-OS/vagrant.template.git"}
      ]
  tasks:
  - debug:
      msg: "{{item.name}}"
    loop: "{{repo}}"

  - name: Git checkout
    ansible.builtin.git:
      repo: "{{item.repo}}"
      dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/src/{{item.subdir}}{{item.name}}"
    loop: "{{repo}}"
