Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu1804"

  # Public Network
  config.vm.define :test_vm1 do |test_vm1|
    test_vm1.vm.network :public_network, :dev => "enp5s0", :mode => 'bridge'
  end

end
