- name: Set Vagrant default provider
  ansible.builtin.lineinfile:
    path: '/home/{{ ansible_env.USER }}/.profile'
    regexp: '^export VAGRANT_DEFAULT_PROVIDER='
    line: 'export VAGRANT_DEFAULT_PROVIDER={{default_provider}}'
    create: true

- name: Set Vagrant's default provider 2
  ansible.builtin.lineinfile:
    path: '/home/{{ ansible_env.USER }}/.bashrc'
    regexp: '^export VAGRANT_DEFAULT_PROVIDER='
    line: 'export VAGRANT_DEFAULT_PROVIDER={{default_provider}}'
    create: true
