# https://developer.hashicorp.com/vagrant/downloads#Linux

# to ansible:
# wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
# echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
# sudo apt update && sudo apt install vagrant

# - name: Doesn't support Newest Ubuntu! If > 22.10, Set to kinetic.
#   set_fact:
#     codename: "{{ ubuntu_latest_supported_codename }}"
#   when: (ansible_distribution_version | replace('.','') | int) >= ubuntu_latest_supported


- name: Download GPG key
  ansible.builtin.shell: wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg
  become: true

- name: Add repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ codename }} main"
    state: present
    filename: hashicorp
  become: true

- name: Install Vagrant
  ansible.builtin.apt:
    pkg:
    - vagrant
  become: true