---
# from: https://vagrant-libvirt.github.io/vagrant-libvirt/
- name: Install Latest
  block:
  - name: Remove old
    ansible.builtin.dnf:
      name: vagrant-libvirt
      state: absent
    notify: Fedora Vagrant libvirt install script
  become: true
  when: latest

- name: Install libvirt-devel
  ansible.builtin.dnf:
    name:
      - libvirt-devel
    state: latest
