#from: https://discussion.fedoraproject.org/t/playing-around-with-fedora-coreos-using-vagrant-libvirt-on-fedora-silverblue/1704/1

- name: To get rid of password prompts for each and every libvirt action
  ansible.builtin.blockinfile:
    path: /etc/polkit-1/rules.d/80-libvirt.rules
    append_newline: true
    prepend_newline: true
    block: |
      polkit.addRule(function(action, subject) {
        if (action.id == "org.libvirt.unix.manage" && subject.local && subject.active && subject.isInGroup("wheel")) {
        return polkit.Result.YES;
        }
      });
  become: true


- name: directory for Dockerfile
  ansible.builtin.file:
    path: "{{ docker_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  become: true

- name: Dockerfile
  ansible.builtin.blockinfile:
    path: "{{ docker_dir }}/Dockerfile"
    create: true
    block: |
      FROM docker://registry.fedoraproject.org/fedora:{{ podman_fedora_version }}
      RUN dnf install -y openssh-clients vagrant vagrant-libvirt
      CMD [ "/bin/bash" ]

- name: Build image
  containers.podman.podman_image:
    name: localhost/vagrant-container:latest
    path: "{{ docker_dir }}/Dockerfile"

- name: Add to shell alias
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    append_newline: true
    prepend_newline: true
    marker_begin: "podman Vagrant BEGIN"
    marker_end: "podman Vagrant END"
    create: true
    block: |
      alias vagrant='podman run --rm -it \
        --volume /run/libvirt:/run/libvirt \
        --volume "${HOME}:${HOME}:rslave" \
        --env "HOME=${HOME}" \
        --workdir "$(pwd)" \
        --net host \
        --privileged \
        --security-opt label=disable \
        --entrypoint /usr/bin/vagrant \
        localhost/vagrant-container:latest'
