- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - libvirt-dev
  become: true

- name: install vagrant-libvirt
  ansible.builtin.shell: vagrant plugin install vagrant-libvirt
  args:
    creates: somelog.txt
