---
- name: Install NFS server
  ansible.builtin.apt:
    pkg:
    - nfs-kernel-server
  become: true


# https://developer.hashicorp.com/vagrant/docs/synced-folders/nfs#root-privilege-requirement
- name: Vagrant Sudoers for NFS (Ubuntu)
  ansible.builtin.blockinfile:
    marker_begin: "<Vagrant"
    marker_end: "Vagrant>"
    path: /etc/sudoers
    block: |
      Cmnd_Alias VAGRANT_EXPORTS_CHOWN = /bin/chown 0\:0 /tmp/vagrant-exports
      Cmnd_Alias VAGRANT_EXPORTS_MV = /bin/mv -f /tmp/vagrant-exports /etc/exports
      Cmnd_Alias VAGRANT_NFSD_CHECK = /etc/init.d/nfs-kernel-server status
      Cmnd_Alias VAGRANT_NFSD_START = /etc/init.d/nfs-kernel-server start
      Cmnd_Alias VAGRANT_NFSD_APPLY = /usr/sbin/exportfs -ar
      %sudo ALL=(root) NOPASSWD: VAGRANT_EXPORTS_CHOWN, VAGRANT_EXPORTS_MV, VAGRANT_NFSD_CHECK, VAGRANT_NFSD_START, VAGRANT_NFSD_APPLY
  become: true