---
- name: test Silverblue 0
  command: which rpm-ostree
  register: rpm_ostree_exists
  changed_when: false
  failed_when: false

- name: test Silverblue 1
  command: which dnf
  register: dnf_exists
  changed_when: false
  failed_when: false

- name: Is Silverblue?
  ansible.builtin.set_fact:
    Silverblue: "{{ true if (rpm_ostree_exists.rc == 0 and dnf_exists.rc == 1) else false }}"
  changed_when: false

- name: test Podman
  command: which podman
  register: podman_exists
  changed_when: false
  failed_when: false

- name: in Container?
  ansible.builtin.set_fact:
    in_container: "{{ false if (podman_exists.rc == 0) else true}}"

- name: Is in Container?
  debug:
    msg: "Is in container? {{in_container}} and Silverblue: {{ Silverblue }}"

- name: Is in Container
  ansible.builtin.include_tasks: rpm.yml
  when: in_container

- name: Silverblue specific tasks
  ansible.builtin.include_tasks: Silverblue.yml
  when: Silverblue

# - name: Fedora pkg
#   ansible.builtin.include_tasks: rpm.yml
#   when: not Silverblue and install_native