- name: create test
  ansible.builtin.file:
    path: "{{ test_dir }}"
    state: directory

- name: vagrant init
  ansible.builtin.shell: vagrant init generic/ubuntu2204
  args:
    chdir: "{{ test_dir }}"
    creates: Vagrantfile

- name: vagrant up
  ansible.builtin.shell: vagrant up
  args:
    chdir: "{{ test_dir }}"
    creates: .vagrant
  async: 3600
  poll: "{{ poll_frequency }}"
