# from: https://vagrant-libvirt.github.io/vagrant-libvirt/installation.html#ubuntu--debian
# Download and execute the vagrant-libvirt-qa install script (installs latest vagrant by default)

- name: Download script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/vagrant-libvirt/vagrant-libvirt-qa/main/scripts/install.bash
    dest: "{{ script }}"
    mode: '0755'

- name: Remove 'qemu' package for Ubuntu >=23.04
  ansible.builtin.replace:
    path: "{{ script }}"
    after: 'function setup_ubuntu()'
    before: 'function setup_distro()'
    regexp: '^        qemu \\\n'
    replace: ''

- name: This command will change the working directory to somedir/ and will only run when somedir/somelog.txt doesn't exist
  ansible.builtin.shell: "{{ script }}"
  args:
    creates: "{{ creates }}"
  become: true
  async: 3600
  poll: 30