Vagrant.configure("2") do |config|

  config.vm.box = "packer/ubuntu-20.04-server-amd64"

  # Name prefix
  config.vm.provider :libvirt do |libvirt|
    libvirt.default_prefix = "server_"
  end

  # Public .Network
  config.vm.define :test_vm1 do |test_vm1|
    test_vm1.vm.network :public_network, :dev => "enp5s0", :mode => 'bridge'
  end

  # Ansible .Provisioner
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
end
