- name: Install Vagrant & plugins
  hosts: localhost
  vars:
    ansible_become_password: u
#    install_source: "Distro Vagrant"

  roles:
    - Vagrant
    # - provider/vagrant-libvirt/package
    # - Synced Folder
    # - .test
