- name: Install Vagrant & plugins
  hosts: localhost
  vars:
    ansible_become_password: u
#    install_source: "Distro Vagrant"

  roles:
    # - Vagrant  
    # vagrant-libvirt will Install latest Vagrant! overwriting default install
    - provider/vagrant-libvirt/package
    # - Synced Folder
